package com.quizapp.db;

import com.quizapp.util.PasswordUtil;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Manages the single SQLite database connection and schema initialization
 * for the Online Quiz Application.
 */
public final class DatabaseManager {

    private static final String DB_URL = "jdbc:sqlite:data/quizapp.db";
    private static Connection connection;

    private DatabaseManager() { }

    /** Returns a shared JDBC connection, creating and initializing the DB if needed. */
    public static synchronized Connection getConnection() {
        if (connection == null) {
            try {
                Class.forName("org.sqlite.JDBC");
                connection = DriverManager.getConnection(DB_URL);
                try (Statement st = connection.createStatement()) {
                    st.execute("PRAGMA foreign_keys = ON;");
                }
                initSchema();
                seedAdmin();
            } catch (ClassNotFoundException | SQLException e) {
                throw new RuntimeException("Failed to initialize database", e);
            }
        }
        return connection;
    }

    private static void initSchema() throws SQLException {
        try (Statement st = connection.createStatement()) {
            st.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    salt TEXT NOT NULL,
                    is_admin INTEGER NOT NULL DEFAULT 0
                );
            """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS quizzes (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    description TEXT,
                    difficulty TEXT DEFAULT 'Medium',
                    time_limit_seconds INTEGER DEFAULT 0,
                    created_by INTEGER,
                    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
                );
            """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS questions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    quiz_id INTEGER NOT NULL,
                    text TEXT NOT NULL,
                    options TEXT NOT NULL,
                    correct_indices TEXT NOT NULL,
                    multiple_answer INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
                );
            """);

            st.execute("""
                CREATE TABLE IF NOT EXISTS attempts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    quiz_id INTEGER NOT NULL,
                    score INTEGER NOT NULL,
                    total_questions INTEGER NOT NULL,
                    attempt_date TEXT NOT NULL,
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
                );
            """);
        }
    }

    /** Creates a default admin account (admin/admin123) on first run, for convenience. */
    private static void seedAdmin() throws SQLException {
        try (Statement st = connection.createStatement();
             var rs = st.executeQuery("SELECT COUNT(*) AS c FROM users WHERE is_admin = 1")) {
            if (rs.next() && rs.getInt("c") == 0) {
                String salt = PasswordUtil.generateSalt();
                String hash = PasswordUtil.hash("admin123", salt);
                try (var ps = connection.prepareStatement(
                        "INSERT INTO users(username, password_hash, salt, is_admin) VALUES (?,?,?,1)")) {
                    ps.setString(1, "admin");
                    ps.setString(2, hash);
                    ps.setString(3, salt);
                    ps.executeUpdate();
                }
            }
        }
    }

    /** Returns the row id generated by the most recent INSERT on this connection. */
    public static synchronized int lastInsertId() {
        try (Statement st = getConnection().createStatement();
             var rs = st.executeQuery("SELECT last_insert_rowid() AS id")) {
            rs.next();
            return rs.getInt("id");
        } catch (SQLException e) {
            throw new RuntimeException("Failed to fetch last insert id", e);
        }
    }

    public static synchronized void close() {
        if (connection != null) {
            try { connection.close(); } catch (SQLException ignored) { }
            connection = null;
        }
    }
}
